# Generated by Django 3.2.4 on 2021-06-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210625_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price2',
            field=models.IntegerField(default=0),
        ),
    ]
