# Generated by Django 3.2.4 on 2021-06-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price2',
        ),
    ]
